[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.30.0", features = ["bundled"] }
argon2 = "0.5.3"
rand = "0.8"
common = { path = "../common" }
tokio = { version = "1", features = ["full"] }
